apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzaXZhMDIuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImMybDJZV055WldRNlFXeHNkWEpwTVRJeiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson

